# fly.toml app configuration file generated for 42backend on 2023-10-19T22:21:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "42backend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  
